name: Feature
description: Requestes or updates a feature
labels: [feature]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Type
      description: Please choose one.
      options:
        - New Feature
        - Update
        - Remove Feature
        - Bug Fix
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A description of the feature / implementation suggestions
    validations:
      required: true
