name: Feature
description: Requestes or updates a feature
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Summary
      description: A brief summary of the feature
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Type
      description: Please choose one.
      options:
        - label: New Feature
        - label: Update
        - label: Remove Feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A description of the feature / implementation suggestions
    validations:
      required: true
