name: Feature
description: Requestes or updates a feature
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Summary
      description: A brief summary of the feature
    validations:
      required: false
  - type: dropdown
    id: feature-type
    attributes:
      label: Type
      description: Please choose one.
      options:
        - New Feature
        - Update
        - Remove Feature
        - Bug Fix
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    validations:
      required: true
